### ISSUE TITLE
Error occurs while installing JSON

### ISSUE THREAD

**Issue by KFad11** [learn-co-curriculum/phrg-javascript-manifests-lab#1]
While running bundle, an error occurs, screenshot below. Deleting the gemlock file and re-running bundle fixed it. 
<img width="743" alt="Screen Shot 2019-06-28 at 11 55 17 AM" src="https://user-images.githubusercontent.com/48073883/60356009-e1e04f80-999d-11e9-9271-54822b7ce55b.png">

**Comment by KFad11** [comment]
@garettarrowood

**Comment by garettarrowood** [comment]
Resolved in https://github.com/learn-co-curriculum/phrg-javascript-manifests-lab/commit/9f88b0b5b135aedbdc6993da170c3907a1d25e0b
